### ISSUE TITLE
Wrong prayer times

### ISSUE THREAD

**Issue by azzamsa** [insha/salah#6]
Since Ragib's [fork](https://github.com/RagibHasin/salah-rs) is not active anymore. I try to revert all my changes to use `insha/salah`. Hoping that it will be fixed here.

``` rust
# I get city coordinates from https://www.mapcoordinates.net/en
let city = Coordinates::new(config.latitude, config.longitude);
let date = Utc::today();    
let params = Configuration::with(Method::Egyptian, Madhab::Shafi);
PrayerTimes::new(date, city, params)
```

But if you see, with the same config as Ragib's fork. I got very different result. Which is not quite right compared to my city prayer schedule.

```
   Compiling bilal v0.1.5 (bilal-project/bilal)
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
     Running `target/debug/bilal -a`
Fajr: 12:55 AM
Sunrise: 12:18 AM
Dhuhr: 4:34 AM
Asr: 7:59 AM
Maghrib: 10:49 AM
Isha: 12:02 PM
Qiyam: 8:14 PM
```

My city schedule:

![image](https://user-images.githubusercontent.com/17734314/104083540-21b21380-5272-11eb-99d4-d873aa45690e.png)

The time for fajr is `12:55 AM`, which the correct one is `03:54 AM`

**Comment by insha** [comment]
@azzamsa What is the city (or coordinates) that you are using? I need those to run through a few tests for this issue and also to make sure the original library is also sound in order to narrow down the issue.

**Comment by azzamsa** [comment]
Isn't this bug [fixed in this comment](https://github.com/insha/salah/issues/1#issuecomment-699438922)

> The problem with wrong Fajr time is due to a bug in SolarTime::setting_hour that I fixed in my fork with RagibHasin/salah-rs@ea23f0c.

---

> I need those to run through a few tests for this issue

nice idea

---

### Long-Lat:

 Central Jakarta (https://www.mapcoordinates.net/en)

```
latitude: -6.18233995
longitude: 106.84287154
```

![image](https://user-images.githubusercontent.com/17734314/104267246-d55e1200-54c3-11eb-99a6-0dc2b750490e.png)

### Local Prayer Times Schedule (https://www.jadwalsholat.org/)

![image](https://user-images.githubusercontent.com/17734314/104267424-3259c800-54c4-11eb-91e1-b6460c01cc99.png)

### insha/salah Schedule

```
❯ cargo r -- -a
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/bilal -a`
Fajr: 12:25 AM
Sunrise: 12:47 AM
Dhuhr: 5:02 AM
Asr: 8:27 AM
Maghrib: 11:14 AM
Isha: 12:27 PM
Qiyam: 8:02 PM
```

### comparison

⚠️: jadwalsholat.org  has been given: 2 minutes for Ihtiyati (safety) time

Prayer Name|insha/salah| jadwalsholat.org | result |
|--|--|--|--|
|Fajr| 12:25 AM|04:15 AM | ❌ |
|Sunsrise| 12:47 AM|05:45 AM | ❌ |
|Duhr| 5:02 AM|12:03 AM | ❌|
|Asr| 8:27 AM|03:28 PM | ❌ |
|Maghrib| 11: 14 AM|06:16 PM | ❌ |
|Isya| 12:27 PM |07:31 PM | ❌ |

Using Ragib's forks, the result will be right. Please take in mind that jadwalsholat.org adds +2 minutes. so without it. Ragib's fork is absolutely close/same.

Prayer Name|ragib/salah| jadwalsholat.org | result |
|--|--|--|--|
|Fajr| 4:27 AM|04:15 AM | ✔️ |
|Sunsrise| 5:47 AM|05:45 AM | ✔️ |
|Duhr| 12:02 AM|12:03 AM | ✔️|
|Asr| 3:27 AM|03:28 PM | ✔️ |
|Maghrib| 6: 14 AM|06:16 PM | ✔️ |
|Isya| 07:27 PM |07:31 PM | ✔️ |

```
❯ cargo r -- -a
    Updating git repository `https://github.com/RagibHasin/salah-rs`
   Compiling salah v0.4.2 (https://github.com/RagibHasin/salah-rs?branch=uptosnuff#fdd27d77)
   Compiling bilal v0.1.5 (/bilal-project/bilal)
    Finished dev [unoptimized + debuginfo] target(s) in 6.09s
     Running `target/debug
Fajr: 4:25 AM
Sunrise: 5:47 AM
Dhuhr: 12:02 PM
Asr: 3:27 PM
Maghrib: 6:14 PM
Isha: 7:27 PM
Qiyam: 1:02 AM
```

**Comment by insha** [comment]
@azzamsa The fork itself cannot be used because it has a lot more changes that are not related to the issue; also that fork does not have any unit tests related to the issue as proof that the fix is a general fix and not associated with a specific location.

That said, I am in the process getting the changes ready for this issue, along with writing tests to confirm the changes are working as expected.

**Comment by insha** [comment]
@azzamsa Please confirm the below for prayer times from the above website 

1. Is the time for _Fajr_ listed under "Shubuh"?
2. Is the time for _Sunrise_ listed under "Terbit"?

**Comment by azzamsa** [comment]
> * Is the time for _Fajr_ listed under "Shubuh"?
> 
> * Is the time for _Sunrise_ listed under "Terbit"?

Yes. Fajr is Shubuh, and Sunrise is Terbit

**Comment by azzamsa** [comment]
I still get the wrong result.

Now, I put all the config in one file. So it easy to reproduce.

```rust
# main.rs

use salah::prelude::*;

fn main() {
    let central_jakarta = Coordinates::new(-6.18233995, 106.84287154);
    let date = Utc.ymd(2020, 1, 13);
    let params = Configuration::with(Method::Egyptian, Madhab::Shafi);
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(central_jakarta)
        .with_configuration(params)
        .calculate();

    match prayers {
        Ok(prayer) => {
            println!(
                "{}: {}",
                Prayer::Fajr.name(),
                prayer.time(Prayer::Fajr).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Sunrise.name(),
                prayer.time(Prayer::Sunrise).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Dhuhr.name(),
                prayer.time(Prayer::Dhuhr).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Asr.name(),
                prayer.time(Prayer::Asr).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Maghrib.name(),
                prayer.time(Prayer::Maghrib).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Isha.name(),
                prayer.time(Prayer::Isha).format("%-l:%M %p").to_string()
            );
            println!(
                "{}: {}",
                Prayer::Qiyam.name(),
                prayer.time(Prayer::Qiyam).format("%-l:%M %p").to_string()
            );
        }
        Err(error) => println!("Could not calculate prayer times: {}", error),
    }
}
```

```bash
❯ cargo r
   Compiling libc v0.2.77
   Compiling num-traits v0.2.12
   Compiling time v0.1.44
   Compiling num-integer v0.1.43
   Compiling chrono v0.4.18
   Compiling salah v0.5.0 (/bilal-project/insha-salah)
   Compiling bilal v0.1.5 (/bilal-project/bilal)
    Finished dev [unoptimized + debuginfo] target(s) in 2.59s
     Running `target/debug/bilal`
Fajr: 9:26 PM
Sunrise: 10:47 PM
Dhuhr: 5:02 AM
Asr: 8:27 AM
Maghrib: 11:15 AM
Isha: 12:27 PM
Qiyam: 6:02 PM
```

Why **fajr** is 9:26 PM, the correct one is around ~04:15 AM.

Am I missing something?

**Comment by insha** [comment]
@azzamsa Yes, you are missing the bit in the readme about the [output being in UTC](https://github.com/insha/salah#date). The library only returns times in UTC, therefore, all clients will need to take the UTC time and convert it to the appropriate local time. You can take a look at the unit test, `calculate_times_for_jakarta()`, in the `lib.rs` for an example of converting the UTC output from the library to the local, to you, Jakarta time.
